name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19

    - name: Test
      run: go test -v ./...

    - name: Update coverage report
      uses: ncruces/go-coverage-report@v0
      with:
        report: true
        chart: true
        amend: true
        reuse-go: true
      continue-on-error: true

    - name: Build with xgo
      uses: crazy-max/ghaction-xgo@v2
      with:
        xgo_version: latest
        go_version: ${{ matrix.go_version }}
        dest: build
        prefix: thriftls
        targets: windows/386,windows/amd64,windows/arm64,linux/386,linux/amd64,linux/arm64,darwin/386,darwin/amd64,darwin/arm64
        v: true
        x: false
        race: false
        ldflags: -s -w
        buildmode: default

#    - uses: "marvinpinto/action-automatic-releases@latest"
#      with:
#        repo_token: "${{ secrets.GITHUB_TOKEN }}"
#        automatic_release_tag: "latest"
#        prerelease: true
#        title: "Development Build"
#        files: |
#            build/thriftls*
#
